# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230801

module OCI
  module DelegateAccessControl::Models
    DELEGATION_CONTROL_RESOURCE_TYPE_ENUM = [
      DELEGATION_CONTROL_RESOURCE_TYPE_VMCLUSTER = 'VMCLUSTER'.freeze,
      DELEGATION_CONTROL_RESOURCE_TYPE_CLOUDVMCLUSTER = 'CLOUDVMCLUSTER'.freeze,
      DELEGATION_CONTROL_RESOURCE_TYPE_EXADBVMCLUSTER = 'EXADBVMCLUSTER'.freeze
    ].freeze
  end
end
