# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20210201
require 'date'
require_relative 'capability_details'

# rubocop:disable Lint/UnneededCopDisableDirective, Metrics/LineLength
module OCI
  # Specifies the details for the consumer group capability.
  # All fields are optional and are only used when the capability is added. Fields will be `null` when the capability is returned as part of the GetQueue API.
  #
  class Queue::Models::ConsumerGroupsCapabilityDetails < Queue::Models::CapabilityDetails
    # Specifies if the primary consumer group should be automatically enabled after adding the capability.
    # @return [BOOLEAN]
    attr_accessor :is_primary_consumer_group_enabled

    # Name of the primary consumer group. If omitted, it will be named \"Primary Consumer Group\".
    # @return [String]
    attr_accessor :primary_consumer_group_display_name

    # The filter used by the primary consumer group. Only messages matching the filter will be available by consumers of the group.
    # An empty value means that all messages will be available in the group.
    #
    # @return [String]
    attr_accessor :primary_consumer_group_filter

    # The number of times a message can be delivered to a consumer before being moved to the dead letter queue.
    # A value of 0 indicates that the DLQ is not used.
    # If the value isn't set, it will be using the value defined at the queue level.
    #
    # @return [Integer]
    attr_accessor :primary_consumer_group_dead_letter_queue_delivery_count

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        # rubocop:disable Style/SymbolLiteral
        'type': :'type',
        'is_primary_consumer_group_enabled': :'isPrimaryConsumerGroupEnabled',
        'primary_consumer_group_display_name': :'primaryConsumerGroupDisplayName',
        'primary_consumer_group_filter': :'primaryConsumerGroupFilter',
        'primary_consumer_group_dead_letter_queue_delivery_count': :'primaryConsumerGroupDeadLetterQueueDeliveryCount'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        # rubocop:disable Style/SymbolLiteral
        'type': :'String',
        'is_primary_consumer_group_enabled': :'BOOLEAN',
        'primary_consumer_group_display_name': :'String',
        'primary_consumer_group_filter': :'String',
        'primary_consumer_group_dead_letter_queue_delivery_count': :'Integer'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:disable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    # @option attributes [BOOLEAN] :is_primary_consumer_group_enabled The value to assign to the {#is_primary_consumer_group_enabled} property
    # @option attributes [String] :primary_consumer_group_display_name The value to assign to the {#primary_consumer_group_display_name} property
    # @option attributes [String] :primary_consumer_group_filter The value to assign to the {#primary_consumer_group_filter} property
    # @option attributes [Integer] :primary_consumer_group_dead_letter_queue_delivery_count The value to assign to the {#primary_consumer_group_dead_letter_queue_delivery_count} property
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      attributes['type'] = 'CONSUMER_GROUPS'

      super(attributes)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      self.is_primary_consumer_group_enabled = attributes[:'isPrimaryConsumerGroupEnabled'] unless attributes[:'isPrimaryConsumerGroupEnabled'].nil?

      raise 'You cannot provide both :isPrimaryConsumerGroupEnabled and :is_primary_consumer_group_enabled' if attributes.key?(:'isPrimaryConsumerGroupEnabled') && attributes.key?(:'is_primary_consumer_group_enabled')

      self.is_primary_consumer_group_enabled = attributes[:'is_primary_consumer_group_enabled'] unless attributes[:'is_primary_consumer_group_enabled'].nil?

      self.primary_consumer_group_display_name = attributes[:'primaryConsumerGroupDisplayName'] if attributes[:'primaryConsumerGroupDisplayName']

      raise 'You cannot provide both :primaryConsumerGroupDisplayName and :primary_consumer_group_display_name' if attributes.key?(:'primaryConsumerGroupDisplayName') && attributes.key?(:'primary_consumer_group_display_name')

      self.primary_consumer_group_display_name = attributes[:'primary_consumer_group_display_name'] if attributes[:'primary_consumer_group_display_name']

      self.primary_consumer_group_filter = attributes[:'primaryConsumerGroupFilter'] if attributes[:'primaryConsumerGroupFilter']

      raise 'You cannot provide both :primaryConsumerGroupFilter and :primary_consumer_group_filter' if attributes.key?(:'primaryConsumerGroupFilter') && attributes.key?(:'primary_consumer_group_filter')

      self.primary_consumer_group_filter = attributes[:'primary_consumer_group_filter'] if attributes[:'primary_consumer_group_filter']

      self.primary_consumer_group_dead_letter_queue_delivery_count = attributes[:'primaryConsumerGroupDeadLetterQueueDeliveryCount'] if attributes[:'primaryConsumerGroupDeadLetterQueueDeliveryCount']

      raise 'You cannot provide both :primaryConsumerGroupDeadLetterQueueDeliveryCount and :primary_consumer_group_dead_letter_queue_delivery_count' if attributes.key?(:'primaryConsumerGroupDeadLetterQueueDeliveryCount') && attributes.key?(:'primary_consumer_group_dead_letter_queue_delivery_count')

      self.primary_consumer_group_dead_letter_queue_delivery_count = attributes[:'primary_consumer_group_dead_letter_queue_delivery_count'] if attributes[:'primary_consumer_group_dead_letter_queue_delivery_count']
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:enable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines


    # Checks equality by comparing each attribute.
    # @param [Object] other the other object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        type == other.type &&
        is_primary_consumer_group_enabled == other.is_primary_consumer_group_enabled &&
        primary_consumer_group_display_name == other.primary_consumer_group_display_name &&
        primary_consumer_group_filter == other.primary_consumer_group_filter &&
        primary_consumer_group_dead_letter_queue_delivery_count == other.primary_consumer_group_dead_letter_queue_delivery_count
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines

    # @see the `==` method
    # @param [Object] other the other object to be compared
    def eql?(other)
      self == other
    end

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [type, is_primary_consumer_group_enabled, primary_consumer_group_display_name, primary_consumer_group_filter, primary_consumer_group_dead_letter_queue_delivery_count].hash
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            public_method("#{key}=").call(
              attributes[self.class.attribute_map[key]]
                .map { |v| OCI::Internal::Util.convert_to_type(Regexp.last_match(1), v) }
            )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          public_method("#{key}=").call(
            OCI::Internal::Util.convert_to_type(type, attributes[self.class.attribute_map[key]])
          )
        end
        # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = public_method(attr).call
        next if value.nil? && !instance_variable_defined?("@#{attr}")

        hash[param] = _to_hash(value)
      end
      hash
    end

    private

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
# rubocop:enable Lint/UnneededCopDisableDirective, Metrics/LineLength
