# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518
require 'date'
require 'logger'

# rubocop:disable Lint/UnneededCopDisableDirective, Metrics/LineLength
module OCI
  # Assessor Summary
  class DatabaseMigration::Models::AssessorSummary
    LIFECYCLE_STATE_ENUM = [
      LIFECYCLE_STATE_ACCEPTED = 'ACCEPTED'.freeze,
      LIFECYCLE_STATE_IN_PROGRESS = 'IN_PROGRESS'.freeze,
      LIFECYCLE_STATE_SUCCEEDED = 'SUCCEEDED'.freeze,
      LIFECYCLE_STATE_NEEDS_ATTENTION = 'NEEDS_ATTENTION'.freeze,
      LIFECYCLE_STATE_FAILED = 'FAILED'.freeze,
      LIFECYCLE_STATE_UNKNOWN_ENUM_VALUE = 'UNKNOWN_ENUM_VALUE'.freeze
    ].freeze

    # **[Required]** The OCID of the resource being referenced.
    # @return [String]
    attr_accessor :assessment_id

    # **[Required]** The Assessor Name.
    # @return [String]
    attr_accessor :name

    # **[Required]** A user-friendly name. Does not have to be unique, and it's changeable.
    # Avoid entering confidential information.
    #
    # @return [String]
    attr_accessor :display_name

    # **[Required]** A user-friendly description. Does not have to be unique, and it's changeable.
    # Avoid entering confidential information.
    #
    # @return [String]
    attr_accessor :description

    # **[Required]** The Help URL.
    # @return [String]
    attr_accessor :help_link_url

    # **[Required]** The Help link text.
    # @return [String]
    attr_accessor :help_link_text

    # **[Required]** The current state of the Assessor.
    # @return [String]
    attr_reader :lifecycle_state

    # @return [OCI::DatabaseMigration::Models::AssessorGroup]
    attr_accessor :assessor_group

    # **[Required]** Assessor actions.
    # @return [Array<OCI::DatabaseMigration::Models::AssessorAction>]
    attr_accessor :actions

    # The Assessor Result text.
    # @return [String]
    attr_accessor :assessor_result

    # The Summary of all Checks.
    # @return [String]
    attr_accessor :checks_summary

    # True if script is available either from 'script' property of through download, false otherwise.
    # @return [BOOLEAN]
    attr_accessor :has_script

    # The generated SQL script. Can be empty if the script exceeds maxLength.
    # In this case the property 'hasScript' indicates that the script is available for download.
    #
    # @return [String]
    attr_accessor :script

    # True if DB restart required after running the script, false otherwise.
    # @return [BOOLEAN]
    attr_accessor :does_script_require_restart

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        # rubocop:disable Style/SymbolLiteral
        'assessment_id': :'assessmentId',
        'name': :'name',
        'display_name': :'displayName',
        'description': :'description',
        'help_link_url': :'helpLinkUrl',
        'help_link_text': :'helpLinkText',
        'lifecycle_state': :'lifecycleState',
        'assessor_group': :'assessorGroup',
        'actions': :'actions',
        'assessor_result': :'assessorResult',
        'checks_summary': :'checksSummary',
        'has_script': :'hasScript',
        'script': :'script',
        'does_script_require_restart': :'doesScriptRequireRestart'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        # rubocop:disable Style/SymbolLiteral
        'assessment_id': :'String',
        'name': :'String',
        'display_name': :'String',
        'description': :'String',
        'help_link_url': :'String',
        'help_link_text': :'String',
        'lifecycle_state': :'String',
        'assessor_group': :'OCI::DatabaseMigration::Models::AssessorGroup',
        'actions': :'Array<OCI::DatabaseMigration::Models::AssessorAction>',
        'assessor_result': :'String',
        'checks_summary': :'String',
        'has_script': :'BOOLEAN',
        'script': :'String',
        'does_script_require_restart': :'BOOLEAN'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:disable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    # @option attributes [String] :assessment_id The value to assign to the {#assessment_id} property
    # @option attributes [String] :name The value to assign to the {#name} property
    # @option attributes [String] :display_name The value to assign to the {#display_name} property
    # @option attributes [String] :description The value to assign to the {#description} property
    # @option attributes [String] :help_link_url The value to assign to the {#help_link_url} property
    # @option attributes [String] :help_link_text The value to assign to the {#help_link_text} property
    # @option attributes [String] :lifecycle_state The value to assign to the {#lifecycle_state} property
    # @option attributes [OCI::DatabaseMigration::Models::AssessorGroup] :assessor_group The value to assign to the {#assessor_group} property
    # @option attributes [Array<OCI::DatabaseMigration::Models::AssessorAction>] :actions The value to assign to the {#actions} property
    # @option attributes [String] :assessor_result The value to assign to the {#assessor_result} property
    # @option attributes [String] :checks_summary The value to assign to the {#checks_summary} property
    # @option attributes [BOOLEAN] :has_script The value to assign to the {#has_script} property
    # @option attributes [String] :script The value to assign to the {#script} property
    # @option attributes [BOOLEAN] :does_script_require_restart The value to assign to the {#does_script_require_restart} property
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      self.assessment_id = attributes[:'assessmentId'] if attributes[:'assessmentId']

      raise 'You cannot provide both :assessmentId and :assessment_id' if attributes.key?(:'assessmentId') && attributes.key?(:'assessment_id')

      self.assessment_id = attributes[:'assessment_id'] if attributes[:'assessment_id']

      self.name = attributes[:'name'] if attributes[:'name']

      self.display_name = attributes[:'displayName'] if attributes[:'displayName']

      raise 'You cannot provide both :displayName and :display_name' if attributes.key?(:'displayName') && attributes.key?(:'display_name')

      self.display_name = attributes[:'display_name'] if attributes[:'display_name']

      self.description = attributes[:'description'] if attributes[:'description']

      self.help_link_url = attributes[:'helpLinkUrl'] if attributes[:'helpLinkUrl']

      raise 'You cannot provide both :helpLinkUrl and :help_link_url' if attributes.key?(:'helpLinkUrl') && attributes.key?(:'help_link_url')

      self.help_link_url = attributes[:'help_link_url'] if attributes[:'help_link_url']

      self.help_link_text = attributes[:'helpLinkText'] if attributes[:'helpLinkText']

      raise 'You cannot provide both :helpLinkText and :help_link_text' if attributes.key?(:'helpLinkText') && attributes.key?(:'help_link_text')

      self.help_link_text = attributes[:'help_link_text'] if attributes[:'help_link_text']

      self.lifecycle_state = attributes[:'lifecycleState'] if attributes[:'lifecycleState']

      raise 'You cannot provide both :lifecycleState and :lifecycle_state' if attributes.key?(:'lifecycleState') && attributes.key?(:'lifecycle_state')

      self.lifecycle_state = attributes[:'lifecycle_state'] if attributes[:'lifecycle_state']

      self.assessor_group = attributes[:'assessorGroup'] if attributes[:'assessorGroup']

      raise 'You cannot provide both :assessorGroup and :assessor_group' if attributes.key?(:'assessorGroup') && attributes.key?(:'assessor_group')

      self.assessor_group = attributes[:'assessor_group'] if attributes[:'assessor_group']

      self.actions = attributes[:'actions'] if attributes[:'actions']

      self.assessor_result = attributes[:'assessorResult'] if attributes[:'assessorResult']

      raise 'You cannot provide both :assessorResult and :assessor_result' if attributes.key?(:'assessorResult') && attributes.key?(:'assessor_result')

      self.assessor_result = attributes[:'assessor_result'] if attributes[:'assessor_result']

      self.checks_summary = attributes[:'checksSummary'] if attributes[:'checksSummary']

      raise 'You cannot provide both :checksSummary and :checks_summary' if attributes.key?(:'checksSummary') && attributes.key?(:'checks_summary')

      self.checks_summary = attributes[:'checks_summary'] if attributes[:'checks_summary']

      self.has_script = attributes[:'hasScript'] unless attributes[:'hasScript'].nil?
      self.has_script = false if has_script.nil? && !attributes.key?(:'hasScript') # rubocop:disable Style/StringLiterals

      raise 'You cannot provide both :hasScript and :has_script' if attributes.key?(:'hasScript') && attributes.key?(:'has_script')

      self.has_script = attributes[:'has_script'] unless attributes[:'has_script'].nil?
      self.has_script = false if has_script.nil? && !attributes.key?(:'hasScript') && !attributes.key?(:'has_script') # rubocop:disable Style/StringLiterals

      self.script = attributes[:'script'] if attributes[:'script']

      self.does_script_require_restart = attributes[:'doesScriptRequireRestart'] unless attributes[:'doesScriptRequireRestart'].nil?
      self.does_script_require_restart = false if does_script_require_restart.nil? && !attributes.key?(:'doesScriptRequireRestart') # rubocop:disable Style/StringLiterals

      raise 'You cannot provide both :doesScriptRequireRestart and :does_script_require_restart' if attributes.key?(:'doesScriptRequireRestart') && attributes.key?(:'does_script_require_restart')

      self.does_script_require_restart = attributes[:'does_script_require_restart'] unless attributes[:'does_script_require_restart'].nil?
      self.does_script_require_restart = false if does_script_require_restart.nil? && !attributes.key?(:'doesScriptRequireRestart') && !attributes.key?(:'does_script_require_restart') # rubocop:disable Style/StringLiterals
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:enable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] lifecycle_state Object to be assigned
    def lifecycle_state=(lifecycle_state)
      # rubocop:disable Style/ConditionalAssignment
      if lifecycle_state && !LIFECYCLE_STATE_ENUM.include?(lifecycle_state)
        OCI.logger.debug("Unknown value for 'lifecycle_state' [" + lifecycle_state + "]. Mapping to 'LIFECYCLE_STATE_UNKNOWN_ENUM_VALUE'") if OCI.logger
        @lifecycle_state = LIFECYCLE_STATE_UNKNOWN_ENUM_VALUE
      else
        @lifecycle_state = lifecycle_state
      end
      # rubocop:enable Style/ConditionalAssignment
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines


    # Checks equality by comparing each attribute.
    # @param [Object] other the other object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        assessment_id == other.assessment_id &&
        name == other.name &&
        display_name == other.display_name &&
        description == other.description &&
        help_link_url == other.help_link_url &&
        help_link_text == other.help_link_text &&
        lifecycle_state == other.lifecycle_state &&
        assessor_group == other.assessor_group &&
        actions == other.actions &&
        assessor_result == other.assessor_result &&
        checks_summary == other.checks_summary &&
        has_script == other.has_script &&
        script == other.script &&
        does_script_require_restart == other.does_script_require_restart
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines

    # @see the `==` method
    # @param [Object] other the other object to be compared
    def eql?(other)
      self == other
    end

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [assessment_id, name, display_name, description, help_link_url, help_link_text, lifecycle_state, assessor_group, actions, assessor_result, checks_summary, has_script, script, does_script_require_restart].hash
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            public_method("#{key}=").call(
              attributes[self.class.attribute_map[key]]
                .map { |v| OCI::Internal::Util.convert_to_type(Regexp.last_match(1), v) }
            )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          public_method("#{key}=").call(
            OCI::Internal::Util.convert_to_type(type, attributes[self.class.attribute_map[key]])
          )
        end
        # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = public_method(attr).call
        next if value.nil? && !instance_variable_defined?("@#{attr}")

        hash[param] = _to_hash(value)
      end
      hash
    end

    private

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
# rubocop:enable Lint/UnneededCopDisableDirective, Metrics/LineLength
