# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518
require 'date'
require_relative 'create_assessment_details'

# rubocop:disable Lint/UnneededCopDisableDirective, Metrics/LineLength
module OCI
  # Create Oracle Assessment resource parameters.
  class DatabaseMigration::Models::CreateOracleAssessmentDetails < DatabaseMigration::Models::CreateAssessmentDetails
    MIGRATION_SCOPE_ENUM = [
      MIGRATION_SCOPE_SCHEMA = 'SCHEMA'.freeze,
      MIGRATION_SCOPE_FULL = 'FULL'.freeze
    ].freeze

    # **[Required]** Assessment migration scope.
    # @return [String]
    attr_reader :migration_scope

    # Database objects to exclude from migration, cannot be specified alongside 'includeObjects'
    #
    # @return [Array<OCI::DatabaseMigration::Models::OracleDatabaseObject>]
    attr_accessor :exclude_objects

    # Database objects to include from migration, cannot be specified alongside 'excludeObjects'
    # @return [Array<OCI::DatabaseMigration::Models::OracleDatabaseObject>]
    attr_accessor :include_objects

    # Specifies the database objects to be excluded from the migration in bulk.
    # The definition accepts input in a CSV format, newline separated for each entry.
    # More details can be found in the documentation.
    #
    # @return [String]
    attr_accessor :bulk_include_exclude_data

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        # rubocop:disable Style/SymbolLiteral
        'description': :'description',
        'compartment_id': :'compartmentId',
        'database_combination': :'databaseCombination',
        'display_name': :'displayName',
        'network_speed_megabit_per_second': :'networkSpeedMegabitPerSecond',
        'acceptable_downtime': :'acceptableDowntime',
        'database_data_size': :'databaseDataSize',
        'ddl_expectation': :'ddlExpectation',
        'creation_type': :'creationType',
        'source_database_connection': :'sourceDatabaseConnection',
        'target_database_connection': :'targetDatabaseConnection',
        'freeform_tags': :'freeformTags',
        'defined_tags': :'definedTags',
        'migration_scope': :'migrationScope',
        'exclude_objects': :'excludeObjects',
        'include_objects': :'includeObjects',
        'bulk_include_exclude_data': :'bulkIncludeExcludeData'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        # rubocop:disable Style/SymbolLiteral
        'description': :'String',
        'compartment_id': :'String',
        'database_combination': :'String',
        'display_name': :'String',
        'network_speed_megabit_per_second': :'String',
        'acceptable_downtime': :'String',
        'database_data_size': :'String',
        'ddl_expectation': :'String',
        'creation_type': :'String',
        'source_database_connection': :'OCI::DatabaseMigration::Models::SourceAssessmentConnection',
        'target_database_connection': :'OCI::DatabaseMigration::Models::TargetAssessmentConnection',
        'freeform_tags': :'Hash<String, String>',
        'defined_tags': :'Hash<String, Hash<String, Object>>',
        'migration_scope': :'String',
        'exclude_objects': :'Array<OCI::DatabaseMigration::Models::OracleDatabaseObject>',
        'include_objects': :'Array<OCI::DatabaseMigration::Models::OracleDatabaseObject>',
        'bulk_include_exclude_data': :'String'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:disable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    # @option attributes [String] :description The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#description #description} proprety
    # @option attributes [String] :compartment_id The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#compartment_id #compartment_id} proprety
    # @option attributes [String] :display_name The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#display_name #display_name} proprety
    # @option attributes [String] :network_speed_megabit_per_second The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#network_speed_megabit_per_second #network_speed_megabit_per_second} proprety
    # @option attributes [String] :acceptable_downtime The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#acceptable_downtime #acceptable_downtime} proprety
    # @option attributes [String] :database_data_size The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#database_data_size #database_data_size} proprety
    # @option attributes [String] :ddl_expectation The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#ddl_expectation #ddl_expectation} proprety
    # @option attributes [String] :creation_type The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#creation_type #creation_type} proprety
    # @option attributes [OCI::DatabaseMigration::Models::SourceAssessmentConnection] :source_database_connection The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#source_database_connection #source_database_connection} proprety
    # @option attributes [OCI::DatabaseMigration::Models::TargetAssessmentConnection] :target_database_connection The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#target_database_connection #target_database_connection} proprety
    # @option attributes [Hash<String, String>] :freeform_tags The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#freeform_tags #freeform_tags} proprety
    # @option attributes [Hash<String, Hash<String, Object>>] :defined_tags The value to assign to the {OCI::DatabaseMigration::Models::CreateAssessmentDetails#defined_tags #defined_tags} proprety
    # @option attributes [String] :migration_scope The value to assign to the {#migration_scope} property
    # @option attributes [Array<OCI::DatabaseMigration::Models::OracleDatabaseObject>] :exclude_objects The value to assign to the {#exclude_objects} property
    # @option attributes [Array<OCI::DatabaseMigration::Models::OracleDatabaseObject>] :include_objects The value to assign to the {#include_objects} property
    # @option attributes [String] :bulk_include_exclude_data The value to assign to the {#bulk_include_exclude_data} property
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      attributes['databaseCombination'] = 'ORACLE'

      super(attributes)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      self.migration_scope = attributes[:'migrationScope'] if attributes[:'migrationScope']

      raise 'You cannot provide both :migrationScope and :migration_scope' if attributes.key?(:'migrationScope') && attributes.key?(:'migration_scope')

      self.migration_scope = attributes[:'migration_scope'] if attributes[:'migration_scope']

      self.exclude_objects = attributes[:'excludeObjects'] if attributes[:'excludeObjects']

      raise 'You cannot provide both :excludeObjects and :exclude_objects' if attributes.key?(:'excludeObjects') && attributes.key?(:'exclude_objects')

      self.exclude_objects = attributes[:'exclude_objects'] if attributes[:'exclude_objects']

      self.include_objects = attributes[:'includeObjects'] if attributes[:'includeObjects']

      raise 'You cannot provide both :includeObjects and :include_objects' if attributes.key?(:'includeObjects') && attributes.key?(:'include_objects')

      self.include_objects = attributes[:'include_objects'] if attributes[:'include_objects']

      self.bulk_include_exclude_data = attributes[:'bulkIncludeExcludeData'] if attributes[:'bulkIncludeExcludeData']

      raise 'You cannot provide both :bulkIncludeExcludeData and :bulk_include_exclude_data' if attributes.key?(:'bulkIncludeExcludeData') && attributes.key?(:'bulk_include_exclude_data')

      self.bulk_include_exclude_data = attributes[:'bulk_include_exclude_data'] if attributes[:'bulk_include_exclude_data']
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:enable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] migration_scope Object to be assigned
    def migration_scope=(migration_scope)
      raise "Invalid value for 'migration_scope': this must be one of the values in MIGRATION_SCOPE_ENUM." if migration_scope && !MIGRATION_SCOPE_ENUM.include?(migration_scope)

      @migration_scope = migration_scope
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines


    # Checks equality by comparing each attribute.
    # @param [Object] other the other object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        description == other.description &&
        compartment_id == other.compartment_id &&
        database_combination == other.database_combination &&
        display_name == other.display_name &&
        network_speed_megabit_per_second == other.network_speed_megabit_per_second &&
        acceptable_downtime == other.acceptable_downtime &&
        database_data_size == other.database_data_size &&
        ddl_expectation == other.ddl_expectation &&
        creation_type == other.creation_type &&
        source_database_connection == other.source_database_connection &&
        target_database_connection == other.target_database_connection &&
        freeform_tags == other.freeform_tags &&
        defined_tags == other.defined_tags &&
        migration_scope == other.migration_scope &&
        exclude_objects == other.exclude_objects &&
        include_objects == other.include_objects &&
        bulk_include_exclude_data == other.bulk_include_exclude_data
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines

    # @see the `==` method
    # @param [Object] other the other object to be compared
    def eql?(other)
      self == other
    end

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [description, compartment_id, database_combination, display_name, network_speed_megabit_per_second, acceptable_downtime, database_data_size, ddl_expectation, creation_type, source_database_connection, target_database_connection, freeform_tags, defined_tags, migration_scope, exclude_objects, include_objects, bulk_include_exclude_data].hash
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            public_method("#{key}=").call(
              attributes[self.class.attribute_map[key]]
                .map { |v| OCI::Internal::Util.convert_to_type(Regexp.last_match(1), v) }
            )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          public_method("#{key}=").call(
            OCI::Internal::Util.convert_to_type(type, attributes[self.class.attribute_map[key]])
          )
        end
        # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = public_method(attr).call
        next if value.nil? && !instance_variable_defined?("@#{attr}")

        hash[param] = _to_hash(value)
      end
      hash
    end

    private

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
# rubocop:enable Lint/UnneededCopDisableDirective, Metrics/LineLength
