# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20160918
require 'date'
require 'logger'
require_relative 'version_scheme_details'

# rubocop:disable Lint/UnneededCopDisableDirective, Metrics/LineLength
module OCI
  # The update should be applied on the database for the selected version series and preference.
  #
  class Database::Models::VersionSchemeFromVersionSeriesDetails < Database::Models::VersionSchemeDetails
    VERSION_PREFERENCE_ENUM = [
      VERSION_PREFERENCE_ORACLE_DB_N = 'ORACLE_DB_N'.freeze,
      VERSION_PREFERENCE_ORACLE_DB_N_1 = 'ORACLE_DB_N_1'.freeze,
      VERSION_PREFERENCE_ORACLE_DB_N_2 = 'ORACLE_DB_N_2'.freeze,
      VERSION_PREFERENCE_ORACLE_DB_N_3 = 'ORACLE_DB_N_3'.freeze,
      VERSION_PREFERENCE_UNKNOWN_ENUM_VALUE = 'UNKNOWN_ENUM_VALUE'.freeze
    ].freeze

    # **[Required]** The update should be applied on the database for the selected major version series.
    # The value can be provided as 23.X.X.X then 23 major version series will be considered.
    #
    # The list of supported versions can be obtained using the API for the provided shape
    # /20160918/dbVersions?compartmentId=<compartmentId>&dbSystemShape=ExaDbXS
    #
    # @return [String]
    attr_accessor :major_version

    # **[Required]** The update should be applied on the database for the selected version preference. *_N represents the LATEST version
    #
    # For Ex: The current latest version is 23.7.0.0.0,
    # If versionPreference selects option as ORACLE_DB_N then oracle applies the db update with LATEST version (i.e. 23.7.0.0.0)
    # If versionPreference selects option as ORACLE_DB_N_1 then oracle applies the db update with LATEST-1 version (i.e. 23.6.0.0.0)
    # If versionPreference selects option as ORACLE_DB_N_2 then oracle applies the db update with LATEST-2 version (i.e. 23.5.0.0.0)
    #
    # @return [String]
    attr_reader :version_preference

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        # rubocop:disable Style/SymbolLiteral
        'source': :'source',
        'major_version': :'majorVersion',
        'version_preference': :'versionPreference'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        # rubocop:disable Style/SymbolLiteral
        'source': :'String',
        'major_version': :'String',
        'version_preference': :'String'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:disable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    # @option attributes [String] :major_version The value to assign to the {#major_version} property
    # @option attributes [String] :version_preference The value to assign to the {#version_preference} property
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      attributes['source'] = 'VERSION_SERIES'

      super(attributes)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      self.major_version = attributes[:'majorVersion'] if attributes[:'majorVersion']

      raise 'You cannot provide both :majorVersion and :major_version' if attributes.key?(:'majorVersion') && attributes.key?(:'major_version')

      self.major_version = attributes[:'major_version'] if attributes[:'major_version']

      self.version_preference = attributes[:'versionPreference'] if attributes[:'versionPreference']

      raise 'You cannot provide both :versionPreference and :version_preference' if attributes.key?(:'versionPreference') && attributes.key?(:'version_preference')

      self.version_preference = attributes[:'version_preference'] if attributes[:'version_preference']
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:enable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] version_preference Object to be assigned
    def version_preference=(version_preference)
      # rubocop:disable Style/ConditionalAssignment
      if version_preference && !VERSION_PREFERENCE_ENUM.include?(version_preference)
        OCI.logger.debug("Unknown value for 'version_preference' [" + version_preference + "]. Mapping to 'VERSION_PREFERENCE_UNKNOWN_ENUM_VALUE'") if OCI.logger
        @version_preference = VERSION_PREFERENCE_UNKNOWN_ENUM_VALUE
      else
        @version_preference = version_preference
      end
      # rubocop:enable Style/ConditionalAssignment
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines


    # Checks equality by comparing each attribute.
    # @param [Object] other the other object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        source == other.source &&
        major_version == other.major_version &&
        version_preference == other.version_preference
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines

    # @see the `==` method
    # @param [Object] other the other object to be compared
    def eql?(other)
      self == other
    end

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [source, major_version, version_preference].hash
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            public_method("#{key}=").call(
              attributes[self.class.attribute_map[key]]
                .map { |v| OCI::Internal::Util.convert_to_type(Regexp.last_match(1), v) }
            )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          public_method("#{key}=").call(
            OCI::Internal::Util.convert_to_type(type, attributes[self.class.attribute_map[key]])
          )
        end
        # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = public_method(attr).call
        next if value.nil? && !instance_variable_defined?("@#{attr}")

        hash[param] = _to_hash(value)
      end
      hash
    end

    private

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
# rubocop:enable Lint/UnneededCopDisableDirective, Metrics/LineLength
