# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20180222
require 'date'

# rubocop:disable Lint/UnneededCopDisableDirective, Metrics/LineLength
module OCI
  # The properties of the secondary vnics
  class ContainerEngine::Models::CreateVnicDetails
    # Display name for secondary vnic
    # @return [String]
    attr_accessor :display_name

    # Whether to allocate an IPv6 address at instance and VNIC creation from an IPv6 enabled subnet
    #
    # @return [BOOLEAN]
    attr_accessor :assign_ipv6_ip

    # Whether the VNIC should be assigned a public IP address
    #
    # @return [BOOLEAN]
    attr_accessor :assign_public_ip

    # Defined tags for this resource. Each key is predefined and scoped to a namespace.
    # For more information, see [Resource Tags](https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
    # Example: `{\"Operations\": {\"CostCenter\": \"42\"}}`
    #
    # @return [Hash<String, Hash<String, Object>>]
    attr_accessor :defined_tags

    # Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
    # For more information, see [Resource Tags](https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
    # Example: `{\"Department\": \"Finance\"}`
    #
    # @return [Hash<String, String>]
    attr_accessor :freeform_tags

    # The number of ip addresses to attach to secondary vnic
    #
    # @return [Integer]
    attr_accessor :ip_count

    # The application resource that corresponds to this secondary vnic. Used to map pods to this specific vnic for scheduling
    #
    # @return [Array<String>]
    attr_accessor :application_resources

    # A list of IPv6 prefixes from which the VNIC should be assigned an IPv6 address. You can provide only the prefix
    # and OCI selects an available address from the range. You can optionally choose to leave the prefix range empty
    # and instead provide the specific IPv6 address that should be used from within that range.
    #
    # @return [Array<OCI::ContainerEngine::Models::Ipv6AddressIpv6SubnetCidrPairDetails>]
    attr_accessor :ipv6_address_ipv6_subnet_cidr_pair_details

    # A list of the OCIDs of the network security groups (NSGs) to add the VNIC to
    #
    # @return [Array<String>]
    attr_accessor :nsg_ids

    # Whether the source/destination check is disabled on the VNIC
    #
    # @return [BOOLEAN]
    attr_accessor :skip_source_dest_check

    # **[Required]** the ocid of the subnet to create the vnic in
    # @return [String]
    attr_accessor :subnet_id

    # [Security attributes](https://docs.cloud.oracle.com/iaas/Content/zero-trust-packet-routing/zpr-artifacts.htm#security-attributes) are labels
    #         for a resource that can be referenced in a [Zero Trust Packet Routing](https://docs.cloud.oracle.com/iaas/Content/zero-trust-packet-routing/overview.htm)
    #         (ZPR) policy to control access to ZPR-supported resources.
    #
    # @return [Hash<String, Hash<String, Object>>]
    attr_accessor :security_attributes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        # rubocop:disable Style/SymbolLiteral
        'display_name': :'displayName',
        'assign_ipv6_ip': :'assignIpv6Ip',
        'assign_public_ip': :'assignPublicIp',
        'defined_tags': :'definedTags',
        'freeform_tags': :'freeformTags',
        'ip_count': :'ipCount',
        'application_resources': :'applicationResources',
        'ipv6_address_ipv6_subnet_cidr_pair_details': :'ipv6AddressIpv6SubnetCidrPairDetails',
        'nsg_ids': :'nsgIds',
        'skip_source_dest_check': :'skipSourceDestCheck',
        'subnet_id': :'subnetId',
        'security_attributes': :'securityAttributes'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        # rubocop:disable Style/SymbolLiteral
        'display_name': :'String',
        'assign_ipv6_ip': :'BOOLEAN',
        'assign_public_ip': :'BOOLEAN',
        'defined_tags': :'Hash<String, Hash<String, Object>>',
        'freeform_tags': :'Hash<String, String>',
        'ip_count': :'Integer',
        'application_resources': :'Array<String>',
        'ipv6_address_ipv6_subnet_cidr_pair_details': :'Array<OCI::ContainerEngine::Models::Ipv6AddressIpv6SubnetCidrPairDetails>',
        'nsg_ids': :'Array<String>',
        'skip_source_dest_check': :'BOOLEAN',
        'subnet_id': :'String',
        'security_attributes': :'Hash<String, Hash<String, Object>>'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:disable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    # @option attributes [String] :display_name The value to assign to the {#display_name} property
    # @option attributes [BOOLEAN] :assign_ipv6_ip The value to assign to the {#assign_ipv6_ip} property
    # @option attributes [BOOLEAN] :assign_public_ip The value to assign to the {#assign_public_ip} property
    # @option attributes [Hash<String, Hash<String, Object>>] :defined_tags The value to assign to the {#defined_tags} property
    # @option attributes [Hash<String, String>] :freeform_tags The value to assign to the {#freeform_tags} property
    # @option attributes [Integer] :ip_count The value to assign to the {#ip_count} property
    # @option attributes [Array<String>] :application_resources The value to assign to the {#application_resources} property
    # @option attributes [Array<OCI::ContainerEngine::Models::Ipv6AddressIpv6SubnetCidrPairDetails>] :ipv6_address_ipv6_subnet_cidr_pair_details The value to assign to the {#ipv6_address_ipv6_subnet_cidr_pair_details} property
    # @option attributes [Array<String>] :nsg_ids The value to assign to the {#nsg_ids} property
    # @option attributes [BOOLEAN] :skip_source_dest_check The value to assign to the {#skip_source_dest_check} property
    # @option attributes [String] :subnet_id The value to assign to the {#subnet_id} property
    # @option attributes [Hash<String, Hash<String, Object>>] :security_attributes The value to assign to the {#security_attributes} property
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      self.display_name = attributes[:'displayName'] if attributes[:'displayName']

      raise 'You cannot provide both :displayName and :display_name' if attributes.key?(:'displayName') && attributes.key?(:'display_name')

      self.display_name = attributes[:'display_name'] if attributes[:'display_name']

      self.assign_ipv6_ip = attributes[:'assignIpv6Ip'] unless attributes[:'assignIpv6Ip'].nil?

      raise 'You cannot provide both :assignIpv6Ip and :assign_ipv6_ip' if attributes.key?(:'assignIpv6Ip') && attributes.key?(:'assign_ipv6_ip')

      self.assign_ipv6_ip = attributes[:'assign_ipv6_ip'] unless attributes[:'assign_ipv6_ip'].nil?

      self.assign_public_ip = attributes[:'assignPublicIp'] unless attributes[:'assignPublicIp'].nil?

      raise 'You cannot provide both :assignPublicIp and :assign_public_ip' if attributes.key?(:'assignPublicIp') && attributes.key?(:'assign_public_ip')

      self.assign_public_ip = attributes[:'assign_public_ip'] unless attributes[:'assign_public_ip'].nil?

      self.defined_tags = attributes[:'definedTags'] if attributes[:'definedTags']

      raise 'You cannot provide both :definedTags and :defined_tags' if attributes.key?(:'definedTags') && attributes.key?(:'defined_tags')

      self.defined_tags = attributes[:'defined_tags'] if attributes[:'defined_tags']

      self.freeform_tags = attributes[:'freeformTags'] if attributes[:'freeformTags']

      raise 'You cannot provide both :freeformTags and :freeform_tags' if attributes.key?(:'freeformTags') && attributes.key?(:'freeform_tags')

      self.freeform_tags = attributes[:'freeform_tags'] if attributes[:'freeform_tags']

      self.ip_count = attributes[:'ipCount'] if attributes[:'ipCount']

      raise 'You cannot provide both :ipCount and :ip_count' if attributes.key?(:'ipCount') && attributes.key?(:'ip_count')

      self.ip_count = attributes[:'ip_count'] if attributes[:'ip_count']

      self.application_resources = attributes[:'applicationResources'] if attributes[:'applicationResources']

      raise 'You cannot provide both :applicationResources and :application_resources' if attributes.key?(:'applicationResources') && attributes.key?(:'application_resources')

      self.application_resources = attributes[:'application_resources'] if attributes[:'application_resources']

      self.ipv6_address_ipv6_subnet_cidr_pair_details = attributes[:'ipv6AddressIpv6SubnetCidrPairDetails'] if attributes[:'ipv6AddressIpv6SubnetCidrPairDetails']

      raise 'You cannot provide both :ipv6AddressIpv6SubnetCidrPairDetails and :ipv6_address_ipv6_subnet_cidr_pair_details' if attributes.key?(:'ipv6AddressIpv6SubnetCidrPairDetails') && attributes.key?(:'ipv6_address_ipv6_subnet_cidr_pair_details')

      self.ipv6_address_ipv6_subnet_cidr_pair_details = attributes[:'ipv6_address_ipv6_subnet_cidr_pair_details'] if attributes[:'ipv6_address_ipv6_subnet_cidr_pair_details']

      self.nsg_ids = attributes[:'nsgIds'] if attributes[:'nsgIds']

      raise 'You cannot provide both :nsgIds and :nsg_ids' if attributes.key?(:'nsgIds') && attributes.key?(:'nsg_ids')

      self.nsg_ids = attributes[:'nsg_ids'] if attributes[:'nsg_ids']

      self.skip_source_dest_check = attributes[:'skipSourceDestCheck'] unless attributes[:'skipSourceDestCheck'].nil?

      raise 'You cannot provide both :skipSourceDestCheck and :skip_source_dest_check' if attributes.key?(:'skipSourceDestCheck') && attributes.key?(:'skip_source_dest_check')

      self.skip_source_dest_check = attributes[:'skip_source_dest_check'] unless attributes[:'skip_source_dest_check'].nil?

      self.subnet_id = attributes[:'subnetId'] if attributes[:'subnetId']

      raise 'You cannot provide both :subnetId and :subnet_id' if attributes.key?(:'subnetId') && attributes.key?(:'subnet_id')

      self.subnet_id = attributes[:'subnet_id'] if attributes[:'subnet_id']

      self.security_attributes = attributes[:'securityAttributes'] if attributes[:'securityAttributes']

      raise 'You cannot provide both :securityAttributes and :security_attributes' if attributes.key?(:'securityAttributes') && attributes.key?(:'security_attributes')

      self.security_attributes = attributes[:'security_attributes'] if attributes[:'security_attributes']
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:enable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines


    # Checks equality by comparing each attribute.
    # @param [Object] other the other object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        display_name == other.display_name &&
        assign_ipv6_ip == other.assign_ipv6_ip &&
        assign_public_ip == other.assign_public_ip &&
        defined_tags == other.defined_tags &&
        freeform_tags == other.freeform_tags &&
        ip_count == other.ip_count &&
        application_resources == other.application_resources &&
        ipv6_address_ipv6_subnet_cidr_pair_details == other.ipv6_address_ipv6_subnet_cidr_pair_details &&
        nsg_ids == other.nsg_ids &&
        skip_source_dest_check == other.skip_source_dest_check &&
        subnet_id == other.subnet_id &&
        security_attributes == other.security_attributes
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines

    # @see the `==` method
    # @param [Object] other the other object to be compared
    def eql?(other)
      self == other
    end

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [display_name, assign_ipv6_ip, assign_public_ip, defined_tags, freeform_tags, ip_count, application_resources, ipv6_address_ipv6_subnet_cidr_pair_details, nsg_ids, skip_source_dest_check, subnet_id, security_attributes].hash
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            public_method("#{key}=").call(
              attributes[self.class.attribute_map[key]]
                .map { |v| OCI::Internal::Util.convert_to_type(Regexp.last_match(1), v) }
            )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          public_method("#{key}=").call(
            OCI::Internal::Util.convert_to_type(type, attributes[self.class.attribute_map[key]])
          )
        end
        # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = public_method(attr).call
        next if value.nil? && !instance_variable_defined?("@#{attr}")

        hash[param] = _to_hash(value)
      end
      hash
    end

    private

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
# rubocop:enable Lint/UnneededCopDisableDirective, Metrics/LineLength
