# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20210610
require 'date'
require 'logger'

# rubocop:disable Lint/UnneededCopDisableDirective, Metrics/LineLength
module OCI
  # Library usage during a specified time period.
  #
  class Jms::Models::LibraryUsage
    CONFIDENCE_LEVEL_ENUM = [
      CONFIDENCE_LEVEL_HIGH = 'HIGH'.freeze,
      CONFIDENCE_LEVEL_MEDIUM = 'MEDIUM'.freeze,
      CONFIDENCE_LEVEL_LOW = 'LOW'.freeze,
      CONFIDENCE_LEVEL_UNKNOWN_ENUM_VALUE = 'UNKNOWN_ENUM_VALUE'.freeze
    ].freeze

    # **[Required]** The internal identifier of the library.
    #
    # @return [String]
    attr_accessor :library_key

    # **[Required]** The [OCID](https://docs.cloud.oracle.com/Content/General/Concepts/identifiers.htm) of the related fleet.
    #
    # @return [String]
    attr_accessor :fleet_id

    # **[Required]** The name of the library.
    #
    # @return [String]
    attr_accessor :library_name

    # The version of the library.
    #
    # @return [String]
    attr_accessor :library_version

    # Deprecated, use `vulnerabilities` instead.
    # The Common Vulnerabilities and Exposures (CVE) ID.
    #
    # @return [String]
    attr_accessor :cve_id

    # Deprecated, use `highestVulnerabilityScore` instead.
    # The Common Vulnerability Scoring System (CVSS) score. If `cvssScore` is not available, it will be set to -1.0. It is set to 0.0 when `cveId` is null.
    #
    # @return [Float]
    attr_accessor :cvss_score

    # **[Required]** Indicates whether the library was dynamically detected.
    #
    # @return [BOOLEAN]
    attr_accessor :is_dynamically_detected

    # Highest CVSS score among the all vulnerabilities. If highest CVSS score is not available, it will be set to -1.0. It is set to 0.0 when there is no associated vulnerabilities.
    #
    # @return [Float]
    attr_accessor :highest_vulnerability_score

    # The list of library vulnerabilities.
    # @return [Array<OCI::Jms::Models::LibraryVulnerability>]
    attr_accessor :vulnerabilities

    # Confidence level of the assessed library's vulnerabilities.
    # @return [String]
    attr_reader :confidence_level

    # The approximate count of applications using the library.
    #
    # @return [Integer]
    attr_accessor :approximate_application_count

    # The approximate count of Java Server instances using the library.
    #
    # @return [Integer]
    attr_accessor :approximate_java_server_instance_count

    # The approximate count of deployed applications using the library.
    #
    # @return [Integer]
    attr_accessor :approximate_deployed_application_count

    # The approximate count of managed instances using the library.
    #
    # @return [Integer]
    attr_accessor :approximate_managed_instance_count

    # Lower bound of the specified time period filter. JMS provides a view of the data that is _per day_. The query uses only the date element of the parameter.
    # @return [DateTime]
    attr_accessor :time_start

    # Upper bound of the specified time period filter. JMS provides a view of the data that is _per day_. The query uses only the date element of the parameter.
    # @return [DateTime]
    attr_accessor :time_end

    # The date and time the resource was _first_ reported to JMS.
    # This is potentially _before_ the specified time period provided by the filters.
    # For example, a resource can be first reported to JMS before the start of a specified time period,
    # if it is also reported during the time period.
    #
    # @return [DateTime]
    attr_accessor :time_first_seen

    # The date and time the resource was _last_ reported to JMS.
    # This is potentially _after_ the specified time period provided by the filters.
    # For example, a resource can be last reported to JMS before the start of a specified time period,
    # if it is also reported during the time period.
    #
    # @return [DateTime]
    attr_accessor :time_last_seen

    # Deprecated.
    # The date and time of the last CVEs refresh was completed.
    #
    # @return [DateTime]
    attr_accessor :time_last_cve_refreshed

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        # rubocop:disable Style/SymbolLiteral
        'library_key': :'libraryKey',
        'fleet_id': :'fleetId',
        'library_name': :'libraryName',
        'library_version': :'libraryVersion',
        'cve_id': :'cveId',
        'cvss_score': :'cvssScore',
        'is_dynamically_detected': :'isDynamicallyDetected',
        'highest_vulnerability_score': :'highestVulnerabilityScore',
        'vulnerabilities': :'vulnerabilities',
        'confidence_level': :'confidenceLevel',
        'approximate_application_count': :'approximateApplicationCount',
        'approximate_java_server_instance_count': :'approximateJavaServerInstanceCount',
        'approximate_deployed_application_count': :'approximateDeployedApplicationCount',
        'approximate_managed_instance_count': :'approximateManagedInstanceCount',
        'time_start': :'timeStart',
        'time_end': :'timeEnd',
        'time_first_seen': :'timeFirstSeen',
        'time_last_seen': :'timeLastSeen',
        'time_last_cve_refreshed': :'timeLastCveRefreshed'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        # rubocop:disable Style/SymbolLiteral
        'library_key': :'String',
        'fleet_id': :'String',
        'library_name': :'String',
        'library_version': :'String',
        'cve_id': :'String',
        'cvss_score': :'Float',
        'is_dynamically_detected': :'BOOLEAN',
        'highest_vulnerability_score': :'Float',
        'vulnerabilities': :'Array<OCI::Jms::Models::LibraryVulnerability>',
        'confidence_level': :'String',
        'approximate_application_count': :'Integer',
        'approximate_java_server_instance_count': :'Integer',
        'approximate_deployed_application_count': :'Integer',
        'approximate_managed_instance_count': :'Integer',
        'time_start': :'DateTime',
        'time_end': :'DateTime',
        'time_first_seen': :'DateTime',
        'time_last_seen': :'DateTime',
        'time_last_cve_refreshed': :'DateTime'
        # rubocop:enable Style/SymbolLiteral
      }
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:disable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    # @option attributes [String] :library_key The value to assign to the {#library_key} property
    # @option attributes [String] :fleet_id The value to assign to the {#fleet_id} property
    # @option attributes [String] :library_name The value to assign to the {#library_name} property
    # @option attributes [String] :library_version The value to assign to the {#library_version} property
    # @option attributes [String] :cve_id The value to assign to the {#cve_id} property
    # @option attributes [Float] :cvss_score The value to assign to the {#cvss_score} property
    # @option attributes [BOOLEAN] :is_dynamically_detected The value to assign to the {#is_dynamically_detected} property
    # @option attributes [Float] :highest_vulnerability_score The value to assign to the {#highest_vulnerability_score} property
    # @option attributes [Array<OCI::Jms::Models::LibraryVulnerability>] :vulnerabilities The value to assign to the {#vulnerabilities} property
    # @option attributes [String] :confidence_level The value to assign to the {#confidence_level} property
    # @option attributes [Integer] :approximate_application_count The value to assign to the {#approximate_application_count} property
    # @option attributes [Integer] :approximate_java_server_instance_count The value to assign to the {#approximate_java_server_instance_count} property
    # @option attributes [Integer] :approximate_deployed_application_count The value to assign to the {#approximate_deployed_application_count} property
    # @option attributes [Integer] :approximate_managed_instance_count The value to assign to the {#approximate_managed_instance_count} property
    # @option attributes [DateTime] :time_start The value to assign to the {#time_start} property
    # @option attributes [DateTime] :time_end The value to assign to the {#time_end} property
    # @option attributes [DateTime] :time_first_seen The value to assign to the {#time_first_seen} property
    # @option attributes [DateTime] :time_last_seen The value to assign to the {#time_last_seen} property
    # @option attributes [DateTime] :time_last_cve_refreshed The value to assign to the {#time_last_cve_refreshed} property
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      self.library_key = attributes[:'libraryKey'] if attributes[:'libraryKey']

      raise 'You cannot provide both :libraryKey and :library_key' if attributes.key?(:'libraryKey') && attributes.key?(:'library_key')

      self.library_key = attributes[:'library_key'] if attributes[:'library_key']

      self.fleet_id = attributes[:'fleetId'] if attributes[:'fleetId']

      raise 'You cannot provide both :fleetId and :fleet_id' if attributes.key?(:'fleetId') && attributes.key?(:'fleet_id')

      self.fleet_id = attributes[:'fleet_id'] if attributes[:'fleet_id']

      self.library_name = attributes[:'libraryName'] if attributes[:'libraryName']

      raise 'You cannot provide both :libraryName and :library_name' if attributes.key?(:'libraryName') && attributes.key?(:'library_name')

      self.library_name = attributes[:'library_name'] if attributes[:'library_name']

      self.library_version = attributes[:'libraryVersion'] if attributes[:'libraryVersion']

      raise 'You cannot provide both :libraryVersion and :library_version' if attributes.key?(:'libraryVersion') && attributes.key?(:'library_version')

      self.library_version = attributes[:'library_version'] if attributes[:'library_version']

      self.cve_id = attributes[:'cveId'] if attributes[:'cveId']

      raise 'You cannot provide both :cveId and :cve_id' if attributes.key?(:'cveId') && attributes.key?(:'cve_id')

      self.cve_id = attributes[:'cve_id'] if attributes[:'cve_id']

      self.cvss_score = attributes[:'cvssScore'] if attributes[:'cvssScore']

      raise 'You cannot provide both :cvssScore and :cvss_score' if attributes.key?(:'cvssScore') && attributes.key?(:'cvss_score')

      self.cvss_score = attributes[:'cvss_score'] if attributes[:'cvss_score']

      self.is_dynamically_detected = attributes[:'isDynamicallyDetected'] unless attributes[:'isDynamicallyDetected'].nil?

      raise 'You cannot provide both :isDynamicallyDetected and :is_dynamically_detected' if attributes.key?(:'isDynamicallyDetected') && attributes.key?(:'is_dynamically_detected')

      self.is_dynamically_detected = attributes[:'is_dynamically_detected'] unless attributes[:'is_dynamically_detected'].nil?

      self.highest_vulnerability_score = attributes[:'highestVulnerabilityScore'] if attributes[:'highestVulnerabilityScore']

      raise 'You cannot provide both :highestVulnerabilityScore and :highest_vulnerability_score' if attributes.key?(:'highestVulnerabilityScore') && attributes.key?(:'highest_vulnerability_score')

      self.highest_vulnerability_score = attributes[:'highest_vulnerability_score'] if attributes[:'highest_vulnerability_score']

      self.vulnerabilities = attributes[:'vulnerabilities'] if attributes[:'vulnerabilities']

      self.confidence_level = attributes[:'confidenceLevel'] if attributes[:'confidenceLevel']

      raise 'You cannot provide both :confidenceLevel and :confidence_level' if attributes.key?(:'confidenceLevel') && attributes.key?(:'confidence_level')

      self.confidence_level = attributes[:'confidence_level'] if attributes[:'confidence_level']

      self.approximate_application_count = attributes[:'approximateApplicationCount'] if attributes[:'approximateApplicationCount']

      raise 'You cannot provide both :approximateApplicationCount and :approximate_application_count' if attributes.key?(:'approximateApplicationCount') && attributes.key?(:'approximate_application_count')

      self.approximate_application_count = attributes[:'approximate_application_count'] if attributes[:'approximate_application_count']

      self.approximate_java_server_instance_count = attributes[:'approximateJavaServerInstanceCount'] if attributes[:'approximateJavaServerInstanceCount']

      raise 'You cannot provide both :approximateJavaServerInstanceCount and :approximate_java_server_instance_count' if attributes.key?(:'approximateJavaServerInstanceCount') && attributes.key?(:'approximate_java_server_instance_count')

      self.approximate_java_server_instance_count = attributes[:'approximate_java_server_instance_count'] if attributes[:'approximate_java_server_instance_count']

      self.approximate_deployed_application_count = attributes[:'approximateDeployedApplicationCount'] if attributes[:'approximateDeployedApplicationCount']

      raise 'You cannot provide both :approximateDeployedApplicationCount and :approximate_deployed_application_count' if attributes.key?(:'approximateDeployedApplicationCount') && attributes.key?(:'approximate_deployed_application_count')

      self.approximate_deployed_application_count = attributes[:'approximate_deployed_application_count'] if attributes[:'approximate_deployed_application_count']

      self.approximate_managed_instance_count = attributes[:'approximateManagedInstanceCount'] if attributes[:'approximateManagedInstanceCount']

      raise 'You cannot provide both :approximateManagedInstanceCount and :approximate_managed_instance_count' if attributes.key?(:'approximateManagedInstanceCount') && attributes.key?(:'approximate_managed_instance_count')

      self.approximate_managed_instance_count = attributes[:'approximate_managed_instance_count'] if attributes[:'approximate_managed_instance_count']

      self.time_start = attributes[:'timeStart'] if attributes[:'timeStart']

      raise 'You cannot provide both :timeStart and :time_start' if attributes.key?(:'timeStart') && attributes.key?(:'time_start')

      self.time_start = attributes[:'time_start'] if attributes[:'time_start']

      self.time_end = attributes[:'timeEnd'] if attributes[:'timeEnd']

      raise 'You cannot provide both :timeEnd and :time_end' if attributes.key?(:'timeEnd') && attributes.key?(:'time_end')

      self.time_end = attributes[:'time_end'] if attributes[:'time_end']

      self.time_first_seen = attributes[:'timeFirstSeen'] if attributes[:'timeFirstSeen']

      raise 'You cannot provide both :timeFirstSeen and :time_first_seen' if attributes.key?(:'timeFirstSeen') && attributes.key?(:'time_first_seen')

      self.time_first_seen = attributes[:'time_first_seen'] if attributes[:'time_first_seen']

      self.time_last_seen = attributes[:'timeLastSeen'] if attributes[:'timeLastSeen']

      raise 'You cannot provide both :timeLastSeen and :time_last_seen' if attributes.key?(:'timeLastSeen') && attributes.key?(:'time_last_seen')

      self.time_last_seen = attributes[:'time_last_seen'] if attributes[:'time_last_seen']

      self.time_last_cve_refreshed = attributes[:'timeLastCveRefreshed'] if attributes[:'timeLastCveRefreshed']

      raise 'You cannot provide both :timeLastCveRefreshed and :time_last_cve_refreshed' if attributes.key?(:'timeLastCveRefreshed') && attributes.key?(:'time_last_cve_refreshed')

      self.time_last_cve_refreshed = attributes[:'time_last_cve_refreshed'] if attributes[:'time_last_cve_refreshed']
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity
    # rubocop:enable Metrics/MethodLength, Layout/EmptyLines, Style/SymbolLiteral

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] confidence_level Object to be assigned
    def confidence_level=(confidence_level)
      # rubocop:disable Style/ConditionalAssignment
      if confidence_level && !CONFIDENCE_LEVEL_ENUM.include?(confidence_level)
        OCI.logger.debug("Unknown value for 'confidence_level' [" + confidence_level + "]. Mapping to 'CONFIDENCE_LEVEL_UNKNOWN_ENUM_VALUE'") if OCI.logger
        @confidence_level = CONFIDENCE_LEVEL_UNKNOWN_ENUM_VALUE
      else
        @confidence_level = confidence_level
      end
      # rubocop:enable Style/ConditionalAssignment
    end

    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines


    # Checks equality by comparing each attribute.
    # @param [Object] other the other object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        library_key == other.library_key &&
        fleet_id == other.fleet_id &&
        library_name == other.library_name &&
        library_version == other.library_version &&
        cve_id == other.cve_id &&
        cvss_score == other.cvss_score &&
        is_dynamically_detected == other.is_dynamically_detected &&
        highest_vulnerability_score == other.highest_vulnerability_score &&
        vulnerabilities == other.vulnerabilities &&
        confidence_level == other.confidence_level &&
        approximate_application_count == other.approximate_application_count &&
        approximate_java_server_instance_count == other.approximate_java_server_instance_count &&
        approximate_deployed_application_count == other.approximate_deployed_application_count &&
        approximate_managed_instance_count == other.approximate_managed_instance_count &&
        time_start == other.time_start &&
        time_end == other.time_end &&
        time_first_seen == other.time_first_seen &&
        time_last_seen == other.time_last_seen &&
        time_last_cve_refreshed == other.time_last_cve_refreshed
    end
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Layout/EmptyLines

    # @see the `==` method
    # @param [Object] other the other object to be compared
    def eql?(other)
      self == other
    end

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [library_key, fleet_id, library_name, library_version, cve_id, cvss_score, is_dynamically_detected, highest_vulnerability_score, vulnerabilities, confidence_level, approximate_application_count, approximate_java_server_instance_count, approximate_deployed_application_count, approximate_managed_instance_count, time_start, time_end, time_first_seen, time_last_seen, time_last_cve_refreshed].hash
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # rubocop:disable Metrics/AbcSize, Layout/EmptyLines


    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            public_method("#{key}=").call(
              attributes[self.class.attribute_map[key]]
                .map { |v| OCI::Internal::Util.convert_to_type(Regexp.last_match(1), v) }
            )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          public_method("#{key}=").call(
            OCI::Internal::Util.convert_to_type(type, attributes[self.class.attribute_map[key]])
          )
        end
        # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end
    # rubocop:enable Metrics/AbcSize, Layout/EmptyLines

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = public_method(attr).call
        next if value.nil? && !instance_variable_defined?("@#{attr}")

        hash[param] = _to_hash(value)
      end
      hash
    end

    private

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
# rubocop:enable Lint/UnneededCopDisableDirective, Metrics/LineLength
